---
# tasks file for aws_ec2 
- name: Lauching ec2 instance
  ec2:
    key_name: "{{ key }}"
    group_id: "{{ sg_id }}"
    instance_type: "{{ type }}"
    image: "{{ ami }}"
    region: "{{ region_name }}"
    wait: yes
    instance_tags:
      name: "{{ tag_name }}"
    count: 1
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: yes 
- name: Refresh Inventory
  meta: refresh_inventory  

